// API types - these will be generated by orval, but we define them manually for now

export interface HealthResponse {
  status: string;
  timestamp: string;
}

export interface ComponentStatus {
  vector_store: boolean;
  embedding_model: boolean;
  llm_api: boolean;
}

export interface ReadinessResponse {
  ready: boolean;
  components: ComponentStatus;
}

export interface DocumentSummary {
  id: string;
  title: string;
  page_count: number;
  chunk_count: number;
  file_size_bytes?: number;
  uploaded_at: string;
}

export interface DocumentListResponse {
  documents: DocumentSummary[];
  total: number;
  limit_reached: boolean;
}

export interface DocumentUploadResponse {
  id: string;
  title: string;
  page_count: number;
  chunk_count: number;
  sections_detected: string[];
  processing_time_ms: number;
  message: string;
}

export interface ChunkSummary {
  chunk_id: string;
  page_number: number;
  section_title?: string;
  token_count: number;
  preview: string;
}

export interface DocumentDetailResponse {
  id: string;
  title: string;
  page_count: number;
  chunks: ChunkSummary[];
  sections: string[];
  uploaded_at: string;
}

export interface DeleteResponse {
  success: boolean;
  message: string;
  chunks_removed: number;
}

export interface Citation {
  document_id: string;
  document_title: string;
  page_number: number;
  section_title?: string;
  text_snippet: string;
  relevance_score: number;
}

export interface QueryTiming {
  embedding_ms: number;
  search_ms: number;
  llm_ms: number;
  total_ms: number;
}

export interface QueryUsage {
  retrieval_tokens: number;
  llm_input_tokens: number;
  llm_output_tokens: number;
  estimated_cost_usd: number;
  timing?: QueryTiming;
}

export interface QueryResponse {
  answer: string;
  citations: Citation[];
  confidence: 'high' | 'medium' | 'low';
  usage: QueryUsage;
  warning?: string;
}

export interface QueryRequest {
  question: string;
  document_ids?: string[];
  max_citations?: number;
}

export interface SystemLimits {
  max_documents: number;
  max_pages_per_document: number;
  max_file_size_mb: number;
  max_question_length: number;
  max_daily_queries: number;
}

export interface PricingInfo {
  llm_model: string;
  input_token_cost_per_1k: number;
  output_token_cost_per_1k: number;
  embedding_model: string;
}

export interface SystemInfoResponse {
  limits: SystemLimits;
  pricing: PricingInfo;
  version: string;
  environment: string;
}

export interface UsageResponse {
  period: string;
  queries_today: number;
  total_tokens_used: number;
  total_cost_usd: number;
  documents_stored: number;
}

export interface InsufficientEvidenceResponse {
  message: string;
  reason: string;
  suggestions: string[];
  partial_context: Citation[];
}
